import{a as q,S as M,i as a}from"./assets/vendor-BNGoQ6_f.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="https://pixabay.com/api/",B="55699167-49f83dd649e03f32caa262a86";async function h(r,t=1){return(await q.get(P,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more"),R=new M(".gallery a",{captionsData:"alt",captionDelay:250});function m(r){const t=r.map(({webformatURL:s,largeImageURL:c,tags:e,likes:o,views:i,comments:v,downloads:S})=>`
      <li class="gallery-item">
        <a href="${c}">
          <img src="${s}" alt="${e}" />
        </a>

        <div class="info">
          <p><b>Likes</b> ${o}</p>
          <p><b>Views</b> ${i}</p>
          <p><b>Comments</b> ${v}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",t),R.refresh()}function $(){p.innerHTML=""}function y(){f.classList.remove("hidden")}function L(){f.classList.add("hidden")}function b(){g.classList.remove("hidden")}function w(){g.classList.add("hidden")}const u=document.querySelector(".form"),E=document.querySelector(".load-more");let n=1,l="",d=0;u.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.target.elements["search-text"].value.trim(),!l){a.warning({message:"Enter search query!",position:"topRight"});return}n=1,$(),w(),y();try{const t=await h(l,n);if(d=t.totalHits,t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),Math.ceil(d/15)>1?b():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}u.reset()});E.addEventListener("click",async()=>{n+=1,w(),y();try{const r=await h(l,n);m(r.hits);const t=Math.ceil(d/15);n>=t?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b();const s=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:s.height*2,behavior:"smooth"})}catch{a.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
